export const page = {
  SIGNIN: { name: "SIGNIN", path: "/signin" },
  SIGNUP: { name: "SIGNUP", path: "/signup" },
  ANALYTICS: { name: "ANALYTICS", path: "/analytic" },
  DOC_TRACKING: { name: "DOC_TRACKING", path: "/DocTracking" },
  PRODUCTS: { name: "PRODUCTS", path: "/productsPage" },
  DASHBOARD_PAGE: { name: "DASHBOARD_PAGE", path: "/DashboardComp" },
  FORM_PAGE: { name: "FORM_PAGE", path: "/FormPage" },
  INVOICE_HISTORY: { name: "INVOICE_HISTORY", path: "/InvoiceHistory" },
  INVOICE_SAVED: { name: "INVOICE_SAVED", path: "/InvoiceSaved" },
  INVOICE_SENT: { name: "INVOICE_SENT", path: "/InvoiceSent" },
  PO_HISTORY: { name: "PO_HISTORY", path: "/PO-History" },
  PO_INBOX: { name: "PO_INBOX", path: "/PO-Inbox" },
  PO_PROGRESS: { name: "PO_PROGRESS", path: "/PO-InProgress" },
  SHIPMENT_HISTORY: { name: "SHIPMENT_HISTORY", path: "/ShipmentHistory" },
  SHIPMENT_SAVED: { name: "SHIPMENT_SAVED", path: "/ShipmentSaved" },
  SHIPMENT_SENT: { name: "SHIPMENT_SENT", path: "/ShipmentSent" },
  DETAIL_DATA: { name: "DETAIL_DATA", path: "/detildata/:id" },
  SINGLE_PRODUCTS: { name: "SINGLE_PRODUCTS", path: "/singleproduct/:id" },
  CREATE_PRODUCT: { name: "CREATE_PRODUCT", path: "/CreateProduct" },
};
